### PR TITLE
Enhancement: Add Pod Stats

### LINKED ISSUE #4: Add pod stats
Add a way to display the number of contributions between fellows. Make a little leaderboard or similar to motivate people to add new issues!

### PR DESCRIPTION
**Pull request by Krishi-02**
## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

Closes #4 

**Preview:** 
image

image

### CODE REVIEW

**Review by sumana2001 — CHANGES_REQUESTED** [review]
Really great job!😍 A couple of changes:
1. Since we have 15 fellows, the leaderboard is really huge. Also everyone is contributing in teams, so won't it be better to combine members of each team to show the total number of PRs? For example it should show something like this
Team members        PRs merged
Krishi and Ishita                 2

2. Where is the bg1.jpg image being used? If it's not needed please remove it

3. Please fix merge conflicts

**Comment by ishitakapoor26** [comment]
Please check, resolved requested changes.

le

**Review by sumana2001 — CHANGES_REQUESTED** [review]
Please check the responsiveness of the leaderboard character which is very cute😍
Screenshot 2022-07-14 at 7 28 54 PM

**Comment by ishitakapoor26** [comment]
Since phone screen view starts from 287 px, I have added responsiveness from that particular pixle count. You can check now, its working fine.

**Review by sumana2001 — APPROVED** [review]
LGTM!

**Pull request merged**
